---
title: "お知らせ一覧"
---

-   **2026-03-24**: モデル生物を使った研究者のネットワークイベント (金沢大学) に参加し，優秀ポスター賞を受賞しました！

-   **2025-02-04**: 筆頭著者として執筆した論文 (プレプリント) が[bioRxivにて公開](https://doi.org/10.64898/2026.02.04.703736)されました。三重大学医学系研究科，ゼブラフィッシュリサーチセンター・島田康人先生らとの共同研究成果です。

-   **2025-12-19**: Click-qPCRの解説記事が [実験医学2026年1月号 (クローズアップ実験法)](https://www.yodosha.co.jp/jikkenigaku/book/9784758125994/index.html) に掲載されました。

-   **2025-12-04**: 先日PLoS One誌にアクセプトされた論文 ([Housing environment bilaterally alters transcriptomic profile in the rat hippocampal CA1 region](https://doi.org/10.1371/journal.pone.0338190)) が出版されました。

-   **2025-11-20**: 先日Bio-protocol誌にアクセプトされた論文 ([Click-qPCR: A Simple Tool for Interactive qPCR Data Analysis](https://doi.org/10.21769/BioProtoc.5513)) が出版されました。

-   **2025-11-18**: 筆頭著者として執筆した論文 (Housing environment bilaterally alters transcriptomic profile in the rat hippocampal CA1 region) がPLoS One誌にアクセプトされました！山梨大学医学部・篠原良章先生らとの共同研究成果です。

-   **2025-11-09**: 第48回 [日本分子生物学会年会＠横浜]{.underline} (12/3~5) に参加します。1日目 (12/3) にポスター発表を行います。[1P-002, 18:00-19:00]

-   **2025-10-14**: 筆頭著者・責任著者として執筆した論文 (Click-qPCR: A Simple Tool for Interactive qPCR Data Analysis) がBio-protocol誌にアクセプトされました！

-   **2025-09-01**: [ブログ記事](blog/blog_20250901.html)を追加しました。

-   **2025-07-30**: [Achievements](/achievements.html)を更新しました。

-   **2025-06-25**: [ブログ記事](blog/blog_20250625.html)を追加しました。

-   **2025-06-04**: 第48回 [日本神経科学大会＠新潟]{.underline} (7/24〜27) に参加します。3日目 (7/26) にポスター発表を行います。[3P-325, 12:50-13:50]

-   **2025-06-01**: 筆頭著者・責任著者として執筆した論文 (プレプリント) が[bioRxivにて公開](https://doi.org/10.1101/2025.05.29.656779)されました。

-   **2025-05-15**: [ブログ記事](blog/blog_20250515.html)を追加しました。

-   **2025-05-05** 筆頭著者として執筆した論文 (プレプリント) が[bioRxivにて公開](https://doi.org/10.1101/2025.04.29.651351)されました。

-   **2025-04-15**: [researchmapアカウント](https://researchmap.jp/kubo_azu)を作成しました。

-   **2025-04-10**: 第18回 [日本エピジェネティクス研究会年会＠福井]{.underline} (6/18〜20) に参加します。

-   **2025-01-08**: [ブログ記事](blog/blog_20250108.html)を追加しました。

-   **2024-12-01**: [ブログ記事](blog/blog_20241201.html)を追加しました。

-   **2024-11-26**: 第47回 [日本分子生物学会年会＠福岡]{.underline} (11/27〜29) に参加します。

-   **2024-11-24**: [Profile](/profile.html)ページに自己紹介を追加しました。

```{=html}
<!--
.qmdファイル内のリンクでは.htmlを指定
-->
```

-   **2024-11-24**: サイトのデザインを変更しました。

-   **2024-11-23**: サイトを公開しました。
